### PR TITLE
proper .travis.yml

### PR DESCRIPTION
**Pull request by John-Colvin**

### CODE REVIEW

**Comment by s-ludwig** [comment]
With the addons field fixed, Linux now passes down to 2.069.2 (2.071.2 being the oldest version officially supported by vibe.d). Mac still fails due to Homebrew complaining about the Ruby version. Do you think that can be fixed or should be disable the OS X tests for now?

**Comment by John-Colvin** [comment]
travis has an old homebrew on its macOS images, have to update it first to make it work. Should work now

**Comment by John-Colvin** [comment]
it passes :)

**Comment by s-ludwig** [comment]
Nice, thanks! It appears that the capacity for Mac builds has been increased, too, so that it doesn't take half a day before the first job starts.

**Pull request merged**
