### PR TITLE
Replace CI (Travis -> GH) and fix up deprecations

### PR DESCRIPTION
**Pull request by Geod24**
I need this to be able to use dub-registry with vibe.d v0.10.0-beta.1 which removes `vibe.inet.path`.

### CODE REVIEW

**Comment by Geod24** [comment]
CC @s-ludwig

**Comment by Geod24** [comment]
Note that even with this, userman won't be compatible with v0.10.0, for example:
```
../../vibe/userman/source/userman/db/mongo.d(44,30): Error: none of the overloads of template `vibe.db.mongo.collection.MongoCollection.findOne` are callable using argument types `!()(Bson[string], bool[string])`
../../vibe/vibe.d/mongodb/vibe/db/mongo/collection.d(395,7):        Candidates are: `findOne(R = Bson, T, U)(T query, U returnFieldSelector, QueryFlags flags)`
../../vibe/vibe.d/mongodb/vibe/db/mongo/collection.d(427,7):                        `findOne(R = Bson, T)(T query, FindOptions options = FindOptions.init)`
```

CC @WebFreak001

**Comment by s-ludwig** [comment]
Isn't that the `projection` parameter of [`find`](https://www.mongodb.com/docs/manual/reference/method/db.collection.find/#std-label-method-find-projection)? Regarding the API changes, we really should avoid hard breaking changes, there should always be some kind of deprecation phase. Hard breaking changes make it really annoying to upgrade downstream projects, which often include multiple dependency layers, especially if they are neither forward, nor backwards compatible.

**Comment by Geod24** [comment]
Exactly. As it stands, userman has to decide to be compatible with either pre-v0.10.0 vibe.d or post v0.10.0.
Now imagine if you have 4-5 dependencies using vibe.d's mongo code...

**Comment by WebFreak001** [comment]
@Geod24 fixed backwards incompatibility, actually tested a few new methods now, code cleanup: https://github.com/vibe-d/vibe.d/pull/2694

**Comment by Geod24** [comment]
Thanks @WebFreak001 ! In the meantime, can we get this merged @s-ludwig ?
You probably need to disable Travis too.

**Comment by Geod24** [comment]
Proof that the CI works: https://github.com/Geod24/userman/actions/runs/3344542825

**Comment by WebFreak001** [comment]
new CI run: https://github.com/Geod24/userman/actions/runs/3347160793

**Comment by Geod24** [comment]
@s-ludwig : Can we get a merge on this ? The fixes to MongoDB will come in another PR.

**Comment by Geod24** [comment]
@s-ludwig : Can we get a new release ? I can't do it myself.

**Pull request merged**
